sudo: required
services:
  - docker

  before_install:
    - docker build -t yaellevy/docker-react -f Dockerfile.dev .

script:
   # - docker run -e CI=true yaellevy/docker-react npm run test - this is not good since it will wait for response
  - docker run yaellevy/docker-react npm run test -- --coverage
  